export const COLOR_PRESETS = [
  {
    id: "blue",
    bg: "#EFF6FF",
    border: "#3B82F6",
    text: "#1D4ED8",
    badge: "#DBEAFE",
  },
  {
    id: "green",
    bg: "#F0FDF4",
    border: "#22C55E",
    text: "#15803D",
    badge: "#DCFCE7",
  },
  {
    id: "purple",
    bg: "#FDF4FF",
    border: "#A855F7",
    text: "#7E22CE",
    badge: "#F3E8FF",
  },
  {
    id: "amber",
    bg: "#FFFBEB",
    border: "#F59E0B",
    text: "#B45309",
    badge: "#FEF3C7",
  },
  {
    id: "rose",
    bg: "#FFF1F2",
    border: "#F43F5E",
    text: "#BE123C",
    badge: "#FFE4E6",
  },
  {
    id: "orange",
    bg: "#FFF7ED",
    border: "#FB923C",
    text: "#C2410C",
    badge: "#FFEDD5",
  },
  {
    id: "teal",
    bg: "#F0FDFA",
    border: "#14B8A6",
    text: "#0F766E",
    badge: "#CCFBF1",
  },
  {
    id: "sky",
    bg: "#F0F9FF",
    border: "#0EA5E9",
    text: "#0369A1",
    badge: "#E0F2FE",
  },
  {
    id: "indigo",
    bg: "#EEF2FF",
    border: "#6366F1",
    text: "#4338CA",
    badge: "#E0E7FF",
  },
  {
    id: "pink",
    bg: "#FDF2F8",
    border: "#EC4899",
    text: "#BE185D",
    badge: "#FCE7F3",
  },
  {
    id: "lime",
    bg: "#F7FEE7",
    border: "#84CC16",
    text: "#4D7C0F",
    badge: "#ECFCCB",
  },
  {
    id: "slate",
    bg: "#F8FAFC",
    border: "#64748B",
    text: "#334155",
    badge: "#E2E8F0",
  },
  {
    id: "red",
    bg: "#FEF2F2",
    border: "#EF4444",
    text: "#B91C1C",
    badge: "#FEE2E2",
  },
  {
    id: "cyan",
    bg: "#ECFEFF",
    border: "#06B6D4",
    text: "#0E7490",
    badge: "#CFFAFE",
  },
  {
    id: "fuchsia",
    bg: "#FDF4FF",
    border: "#D946EF",
    text: "#A21CAF",
    badge: "#FAE8FF",
  },
  {
    id: "stone",
    bg: "#FAFAF9",
    border: "#78716C",
    text: "#44403C",
    badge: "#F5F5F4",
  },
];
